version: '2'
volumes:
  node_modules:
services:
  devserver:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "35729:35729"
    command: bash -c "yarn && yarn run start"
    volumes:
      - .:/app
      - node_modules:/app/node_modules